CREATE DATABASE MARS CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE MARS.SHOPS (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LATITUDE DOUBLE(10, 7) NOT NULL,
    LONGITUDE DOUBLE(10, 7) NOT NULL,
    CATEGORY VARCHAR(256),
    SHOPNAME VARCHAR(256),
    OPENINGHOURS VARCHAR(256),
    WEBSITE VARCHAR(256)
);

CREATE TABLE MARS.POIS(
    ID VARCHAR(256) NOT NULL PRIMARY KEY,
    LATITUDE DOUBLE(10, 7) NOT NULL,
    LONGITUDE DOUBLE(10, 7) NOT NULL,
    PNAME VARCHAR(256) NOT NULL
);

CREATE TABLE MARS.FAVOURITES(
    FNAME VARCHAR(256) NOT NULL PRIMARY KEY,
    SCATEGORY VARCHAR(256),
    SNAME VARCHAR(256),
    SPOI VARCHAR(256),
    FOREIGN KEY (SPOI)
        REFERENCES MARS.POIS (ID)
                ON UPDATE CASCADE ON DELETE SET NULL,
    SDISTANCE INT
);

LOAD DATA INFILE '/tmp/final.csv' 
    INTO TABLE MARS.SHOPS 
    CHARACTER SET utf8
    FIELDS TERMINATED BY ';'
    (LATITUDE, LONGITUDE, CATEGORY, SHOPNAME, OPENINGHOURS, WEBSITE)
    SET ID = NULL;
LOAD DATA INFILE '/tmp/graz_poi_complete.csv' 
    INTO TABLE MARS.POIS 
    CHARACTER SET utf8
    FIELDS TERMINATED BY '|'
    IGNORE 1 LINES;
